### ISSUE TITLE
Refresh the code

### ISSUE THREAD

**Issue by jdfekete** [jdfekete/reorder.js#19]
@curran wrote: Another adjacent thought - if we were to really deeply refresh this library, we could also take a stylistic pass over the codebase and adopt let and const, and arrow function expressions. Also Prettier for code formatting would probably be a good move.

**Comment by curran** [comment]
Breakdown of tasks:
 * [X] Prettier
 * [ ] let and const, and arrow function expressions
 
 Maybe we can automate it with [Lebab](https://github.com/lebab/lebab).
 
 Here's some sample output comparison using Lebab:

![image](https://user-images.githubusercontent.com/68416/103426169-8809a880-4b85-11eb-880a-373fc1c6ae95.png)

Looks decent as a first pass. Then after that, manual tweaks can be made such as inlining the `let i` for instance.

**Comment by curran** [comment]
For "let and const, and arrow function expressions", we can break it down as follows:

### Phase I: Automatic Refresh
 * [ ] Apply automatic upgrades using Lebab across all code

### Phase II: Manual Clean Up of All Files
The main task, I think, will be inlining `let` into `for` loops where possible.

 * [ ] src/adjacent_exchange.js
 * [ ] src/aliases.js
 * [ ] src/all_pairs_distance.js
 * [ ] src/bandwidth.js
 * [ ] src/barycenter_order.js
 * [ ] src/bfs.js
 * [ ] src/bfs_order.js
 * [ ] src/ca.js
 * [ ] src/condition.js
 * [ ] src/core.js
 * [ ] src/correlation.js
 * [ ] src/count_crossings.js
 * [ ] src/covariance.js
 * [ ] src/cuthill_mckee_order.js
 * [ ] src/debug.js
 * [ ] src/distance.js
 * [ ] src/dist.js
 * [ ] src/edgesum.js
 * [ ] src/fiedler.js
 * [ ] src/graph2distmat.js
 * [ ] src/graph2mat.js
 * [ ] src/graph_complete.js
 * [ ] src/graph_connect.js
 * [ ] src/graph_empty.js
 * [ ] src/graph.js
 * [ ] src/graph_random.js
 * [ ] src/hcluster.js
 * [ ] src/index.js
 * [ ] src/intersect.js
 * [ ] src/laplacian.js
 * [ ] src/mat2graph.js
 * [ ] src/mean.js
 * [ ] src/optimal_leaf_order.js
 * [ ] src/order.js
 * [ ] src/pca_order.js
 * [ ] src/pcp.js
 * [ ] src/permutation.js
 * [ ] src/permute.js
 * [ ] src/poweriteration.js
 * [ ] src/random.js
 * [ ] src/range.js
 * [ ] src/sort_order.js
 * [ ] src/spectral_order.js
 * [ ] src/stablepermute.js
 * [ ] src/sum.js
 * [ ] src/transpose.js
 * [ ] src/utils.js
 * [ ] test/all_pairs_distance-test.js
 * [ ] test/barycenter-test.js
 * [ ] test/bfs-test.js
 * [ ] test/ca-test.js
 * [ ] test/components-test.js
 * [ ] test/count_crossings-test.js
 * [ ] test/cuthill_mckee-test.js
 * [ ] test/env-assert.js
 * [ ] test/graph2distmat-test.js
 * [ ] test/graph2mat-test.js
 * [ ] test/graph-test.js
 * [ ] test/laplacian-test.js
 * [ ] test/leaforder-test.html
 * [ ] test/leaforder-test.js
 * [ ] test/mat2graph-test.js
 * [ ] test/order-test.html
 * [ ] test/order-test.js
 * [ ] test/pca1d-test.js
 * [ ] test/pcp-test.js
 * [ ] test/pearson-test.js
 * [ ] test/permute-test.js
